import turtle
t = turtle.Turtle()
start_match = input("Start Match")
if start_match == "Start":
    
    t.speed(0)
    t.fd(300)
    t.bk(400)
    t.fd(100)
    t.rt(90)
    t.fd(200)
    t.bk(300)
    t.fd(100)
    t.lt(90)
    t.fd(100)
    t.rt(90)
    t.fd(300)
    t.bk(400)
    t.fd(200)
    t.rt(90)
    t.fd(200)
    t.bk(300)
    t.penup()
def Player_X():
    place = input("Player X's turn")
    if place == "(1,1)":
        t.penup()
        t.goto(-75,15)
        t.pendown()
        t.rt(120)
        t.fd(60)
        t.bk(30)
        t.lt(90)
        t.fd(30)
        t.bk(60)
        t.penup()
        t.lt(30)
    elif place == "(1,2)":
        t.penup()
        t.goto(15,15)
        t.pendown()
        t.rt(120)
        t.fd(60)
        t.bk(30)
        t.lt(90)
        t.fd(30)
        t.bk(60)
        t.penup()
        t.lt(30)
    elif place == "(1,3)":
        t.penup()
        t.goto(125,15)
        t.pendown()
        t.rt(120)
        t.fd(60)
        t.bk(30)
        t.lt(90)
        t.fd(30)
        t.bk(60)
        t.penup()
        t.lt(30)
    elif place == "(2,1)":
        t.penup()
        t.goto(-75,-85)
        t.pendown()
        t.rt(120)
        t.fd(60)
        t.bk(30)
        t.lt(90)
        t.fd(30)
        t.bk(60)
        t.penup()
        t.lt(30)
    elif place == "(2,2)":
        t.penup()
        t.goto(15,-85)
        t.pendown()
        t.rt(120)
        t.fd(60)
        t.bk(30)
        t.lt(90)
        t.fd(30)
        t.bk(60)
        t.penup()
        t.lt(30)
    elif place == "(2,3)":
        t.penup()
        t.goto(125,-85)
        t.pendown()
        t.rt(120)
        t.fd(60)
        t.bk(30)
        t.lt(90)
        t.fd(30)
        t.bk(60)
        t.penup()
        t.lt(30)
    elif place == "(3,1)":
        t.penup()
        t.goto(-75,-185)
        t.pendown()
        t.rt(120)
        t.fd(60)
        t.bk(30)
        t.lt(90)
        t.fd(30)
        t.bk(60)
        t.penup()
        t.lt(30)
    elif place == "(3,2)":
        t.penup()
        t.goto(15,-185)
        t.pendown()
        t.rt(120)
        t.fd(60)
        t.bk(30)
        t.lt(90)
        t.fd(30)
        t.bk(60)
        t.penup()
        t.lt(30)
    elif place == "(3,3)":
        t.penup()
        t.goto(125,-185)
        t.pendown()
        t.rt(120)
        t.fd(60)
        t.bk(30)
        t.lt(90)
        t.fd(30)
        t.bk(60)
        t.penup()
        t.lt(30)

def Player_O():

    place = input("Player O's turn")
    if place == "(1,1)":
        t.penup()
        t.goto(-75,70)
        t.pendown()
        t.circle(35)
        t.penup()
    elif place == "(1,2)":
        t.penup()
        t.goto(15,70)
        t.pendown()
        t.circle(35)
        t.penup()
    elif place == "(1,3)":
        t.penup()
        t.goto(125,70)
        t.pendown()
        t.circle(35)
        t.penup()
    elif place == "(2,1)":
        t.penup()
        t.goto(-75,-15)
        t.pendown()
        t.circle(35)
        t.penup()
    elif place == "(2,2)":
        t.penup()
        t.goto(15,-15)
        t.pendown()
        t.circle(35)
        t.penup()
    elif place == "(2,3)":
        t.penup()
        t.goto(125,-15)
        t.pendown()
        t.circle(35)
        t.penup()
    elif place == "(3,1)":
        t.penup()
        t.goto(-75,-115)
        t.pendown()
        t.circle(35)
        t.penup()
    elif place == "(3,2)":
        t.penup()
        t.goto(15,-115)
        t.pendown()
        t.circle(35)
        t.penup()
    elif place == "(3,3)":
        t.penup()
        t.goto(125,-115)
        t.pendown()
        t.circle(35)
        t.penup()

while True:
    turn = input("Which Player's Turn or End Match")
    if turn == "Player X":
        Player_X()
    if turn == "Player O":
        Player_O()
    if turn == "End Match":
        break
